---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-28d24de43e49220bef03949303416efe
  name: podinfo-test
  namespace: wego-system
spec:
  branch: main
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/jpellizzari/podinfo-deploy-super-long-name-omg-why-is-this-so-long-make-it-stop-pls.git
